# Generated by Django 3.2.5 on 2021-07-08 16:02

import accountapp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]{5,20}$', '5-20글자 사이의 숫자,영문,언더바만 가능합니다!')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('school', models.CharField(choices=[('0', '성균관대학교'), ('1', '광주과학기술원'), ('2', '서강대학교'), ('3', '울산과학기술원'), ('4', '중앙대학교'), ('5', '한국과학기술원'), ('6', '한양대학교')], max_length=2, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('school_status', models.CharField(choices=[('0', '재학'), ('1', '휴학'), ('2', '졸업예정'), ('3', '졸업')], default='0', max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accountapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.SlugField(allow_unicode=True, max_length=10, unique=True)),
                ('github', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='../static/img/profile-default.png', upload_to='profile/')),
                ('type', models.CharField(choices=[('0', '개발자'), ('1', '디자이너'), ('2', '기획자'), ('3', '기타')], default='0', max_length=2)),
                ('status', models.CharField(choices=[('0', '휴식 중'), ('1', '팀 찾는 중'), ('2', '팀 참가 중'), ('3', '기타')], default='3', max_length=2)),
                ('has_entered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('to_open', models.BooleanField(choices=[(False, '자신 학교에만 공개하기'), (True, '모든 학교에 공개하기')], default=False)),
                ('interest', models.ManyToManyField(to='accountapp.Interest')),
                ('stack', models.ManyToManyField(to='accountapp.Stack')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ability', models.CharField(choices=[('0', '초급 (기본적인 대화 가능)'), ('1', '중급 (사무적인 대화 가능)'), ('2', '고급 (자유자재 의사소통)')], default='0', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='accountapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='accountapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='accountapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='accountapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('0', '동아리'), ('1', '프로젝트'), ('2', '기타')], default='0', max_length=1)),
                ('role', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='accountapp.profile')),
            ],
        ),
    ]
