# Generated by Django 3.2.5 on 2021-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_auto_20210719_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../static/img/profile-default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='accountapp.Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.ManyToManyField(blank=True, to='accountapp.Stack'),
        ),
    ]
