# Generated by Django 3.2.5 on 2021-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_auto_20210720_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='self_intro',
            field=models.TextField(blank=True),
        ),
    ]
