# Generated by Django 3.2.5 on 2021-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_profile_self_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(choices=[('0', '성균관대학교'), ('1', '광주과학기술원')], max_length=2, null=True),
        ),
    ]
