# Generated by Django 3.2.5 on 2021-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='to_open',
            field=models.BooleanField(choices=[(False, '학교'), (True, '전체')], default=True),
        ),
    ]
