# Generated by Django 3.2.5 on 2021-10-25 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_alter_profile_to_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=100)),
                ('mail', models.TextField(null=True)),
                ('send_it', models.BooleanField(default=False)),
            ],
        ),
    ]
