# Generated by Django 3.2.5 on 2021-07-15 00:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dev_tags',
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('0', '스터디'), ('1', '프로젝트'), ('2', '대회/공모전'), ('3', '동아리'), ('4', '스타트업')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('서버/백엔드', '서버/백엔드'), ('프론트엔드', '프론트엔드'), ('DevOps', 'DevOps'), ('안드로이드 앱', '안드로이드 앱'), ('아이폰 앱', '아이폰 앱'), ('UI/UX', 'UI/UX'), ('데이터 엔지니어', '데이터 엔지니어'), ('머신러닝/AI', '머신러닝/AI'), ('게임 개발', '게임 개발'), ('AR/VR', 'AR/VR'), ('그래픽 디자인', '그래픽 디자인'), ('임베디드', '임베디드'), ('IoT', 'IoT'), ('보안', '보안'), ('블록체인', '블록체인'), ('알고리즘', '알고리즘'), ('기획/PM', '기획/PM'), ('마케팅', '마케팅'), ('기타', '기타')], max_length=111, null=True),
        ),
    ]
