# Generated by Django 3.2.5 on 2021-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_auto_20210719_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact',
            field=models.CharField(default='등록된 연락처가 없습니다', max_length=1024),
        ),
        migrations.AlterField(
            model_name='team',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, help_text='simple description text.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='../static/img/team-default.jpg', upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_color',
            field=models.CharField(default='rgba(240, 116, 137, 1)', max_length=25),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
