# Generated by Django 3.2.5 on 2021-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_auto_20210720_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
