# Generated by Django 3.2.5 on 2021-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_auto_20210720_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('0', '스터디'), ('1', '프로젝트'), ('2', '대회/공모전'), ('3', '동아리'), ('4', '스타트업/창업')], default='0', max_length=2),
        ),
    ]
