# Generated by Django 3.2.5 on 2021-08-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_alter_contest_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_comment', to='contestapp.contest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
