version: "3.7"
services:
  nginx:
    image: nginx:1.21.1
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80

  web:
    image: django_web:1
    networks:
      - network
    volumes:
      - static-volume:/home/deploy/staticfiles
      - media-volume:/home/deploy/media
    secrets:
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  db:
    image: postgres:13.3
    networks:
      - network
    volumes:
      - postgres-database:/var/lib/data/
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: postgres_db


networks:
  network:

volumes:
  static-volume:
  media-volume:
  postgres-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_USER:
    external: true

