# Generated by Django 3.2.5 on 2021-07-30 22:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('host', models.CharField(max_length=40, null=True)),
                ('participant', models.CharField(max_length=20, null=True)),
                ('homepage', models.URLField(blank=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('0', '기획/아이디어'), ('1', '광고/마케팅'), ('2', '논문/리포트'), ('3', '영상/사진'), ('4', '디자인/캐릭터/웹툰'), ('5', '웹/모바일/IT'), ('6', '게임/소프트웨어'), ('7', '과학/공학'), ('8', '네이밍/슬로건'), ('9', '예체능/미술/음악'), ('10', '대외활동/서포터즈'), ('11', '취업/창업'), ('12', '해외'), ('13', '기타')], max_length=31, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='contest/')),
                ('content', models.TextField(null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
