# Generated by Django 3.2.5 on 2021-08-04 08:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0002_contest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('기획/아이디어', '기획/아이디어'), ('광고/마케팅', '광고/마케팅'), ('논문/리포트', '논문/리포트'), ('영상/사진', '영상/사진'), ('디자인/캐릭터/웹툰', '디자인/캐릭터/웹툰'), ('웹/모바일/IT', '웹/모바일/IT'), ('게임/소프트웨어', '게임/소프트웨어'), ('과학/공학', '과학/공학'), ('네이밍/슬로건', '네이밍/슬로건'), ('예체능/미술/음악', '예체능/미술/음악'), ('대외활동/서포터즈', '대외활동/서포터즈'), ('취업/창업', '취업/창업'), ('해외', '해외'), ('기타', '기타')], max_length=102, null=True),
        ),
    ]
