# Generated by Django 3.2.5 on 2021-08-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0004_auto_20210805_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
