# Generated by Django 3.2.5 on 2021-08-16 21:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0005_auto_20210805_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='image',
        ),
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('기획/아이디어', '기획/아이디어'), ('광고/마케팅', '광고/마케팅'), ('논문/리포트', '논문/리포트'), ('영상/UCC/사진', '영상/UCC/사진'), ('디자인/캐릭터/웹툰', '디자인/캐릭터/웹툰'), ('웹/모바일/IT', '웹/모바일/IT'), ('게임/소프트웨어', '게임/소프트웨어'), ('과학/공학', '과학/공학'), ('문학/글/시나리오', '문학/글/시나리오'), ('건축/건설/인테리어', '건축/건설/인테리어'), ('네이밍/슬로건', '네이밍/슬로건'), ('예체능/미술/음악', '예체능/미술/음악'), ('대외활동/서포터즈', '대외활동/서포터즈'), ('봉사활동', '봉사활동'), ('취업/창업', '취업/창업'), ('해외', '해외'), ('기타', '기타')], max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
