# Generated by Django 3.2.5 on 2021-08-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0006_auto_20210816_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(null=True, upload_to='contest/'),
        ),
    ]
