# Generated by Django 3.2.5 on 2021-09-02 12:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0007_contest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('웹/앱 개발', '웹/앱 개발'), ('게임/VR', '게임/VR'), ('머신러닝/AI', '머신러닝/AI'), ('보안/해킹', '보안/해킹'), ('컴퓨터 그래픽', '컴퓨터 그래픽'), ('빅데이터', '빅데이터'), ('알고리즘', '알고리즘'), ('임베디드', '임베디드'), ('블록체인', '블록체인'), ('기타', '기타')], max_length=57, null=True),
        ),
    ]
