# Generated by Django 3.2.5 on 2021-09-13 13:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0008_alter_contest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SW창업', 'SW창업'), ('웹/앱 개발', '웹/앱 개발'), ('게임', '게임'), ('보안', '보안'), ('AI/빅데이터', 'AI/빅데이터'), ('알고리즘', '알고리즘'), ('임베디드', '임베디드'), ('로봇/자율주행', '로봇/자율주행'), ('AR/VR', 'AR/VR'), ('기타', '기타')], max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
