# Generated by Django 3.2.5 on 2021-09-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0009_auto_20210908_2157'),
        ('contestapp', '0009_auto_20210913_1313'),
    ]

    operations = [
    ]
