# Generated by Django 3.2.5 on 2021-09-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0002_auto_20210913_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text_preview',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
