# Generated by Django 3.2.5 on 2021-09-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0003_notification_text_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Announcement'), (1, 'TeamComment'), (2, 'NewContest')]),
        ),
    ]
