# Generated by Django 3.2.5 on 2021-09-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0004_auto_20210916_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
