# Generated by Django 3.2.5 on 2021-09-19 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0006_auto_20210918_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement_link', models.CharField(blank=True, default='/', max_length=200, null=True)),
            ],
        ),
    ]
