# Generated by Django 3.2.5 on 2021-09-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0007_announcementfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementfield',
            name='announcement_admin',
            field=models.TextField(default='알림 오류', null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='announcement',
            field=models.TextField(null=True),
        ),
    ]
